### ISSUE TITLE
Unable to test out v1 alpha; causing connection lost error

### ISSUE THREAD

**Issue by zucoa** [stefanwalther/sense-navigation#101] opened 2017-11-08 16:48 UTC
### Description

When dragging the v1 alpha extension onto a sheet it will cause Qlik Sense Desktop to generate a connection lost error.

### Steps to Reproduce

1. Add v1 alpha extension to extensions library in dev hub
2. Open app
3. Drag extension into sheet
4. Produces the screenshot attached

##### Expected behavior

Functionality seen with prior next navigation extension.

##### Actual behavior

Connection lost error.

##### Operating system

```
[X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[X] Desktop
[X] Enterprise
```

##### Browser

```
[X] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: v1 alpha
* Browser: Chrome
* Qlik Sense: September 2017 release
* Operating system: Windows
![capture](https://user-images.githubusercontent.com/22177573/32561598-a3089eba-c47a-11e7-8feb-b92724da677b.PNG)

* [Other relevant versions]

**Comment by stefanwalther** [comment] 2017-11-08 22:37
Thx for reporting, will test; did you test without DevHub?

**Comment by zucoa** [comment] 2017-11-09 12:31
Not sure I follow. When I add extensions in my directory Qlik\Sense\Extensions it automatically gets added to the extensions list in DevHub. Do you have another method in order to test?

**Comment by stefanwalther** [comment] 2017-11-09 16:58
Another question, could you pls have a look into the Browsers Dev Concole (e.g. Chrome Dev Tools) if there is any message/error in the console, thx.

**Comment by rjriel** [comment] 2017-11-09 23:35
Was able to reproduce this. Issue occurred when I drag/dropped the extension onto the canvas and it loaded. If you refresh the page so the extension loads again, you'll get the same error.

However, if you hit the "close" button on that popup instead of "refresh" you can continue on as if nothing happened and the extensions will work.

Nothing shows up in the console. I'll look through the websocket frames but at first glance I wasn't seeing anything there either.

**Comment by rjriel** [comment] 2017-11-10 01:15
Ok, after some long debugging I've narrowed it down to [here](https://github.com/stefanwalther/sense-navigation/blob/99e5a2c2893a3e4adb040320da99116b48b3b08f/src/properties.js#L271). If I comment that line (the call to ppHelper.getAppList) out, I don't get the connection lost message. I've confirmed it's not a result of the ppHelper code directly

**Comment by zucoa** [comment] 2017-11-10 20:11
@rjriel Great debugging! @stefanwalther Did you want me to test anything else out or is rjiel on to a potential fix?

**Comment by stefanwalther** [comment] 2017-11-11 00:29
Hmmm, I cannot reproduce it at all ... I suggest we take it 1:1 in Ottawa next week.

**Comment by rjriel** [comment] 2017-11-11 00:36
sure thing.

Forgot to mention this is on Qlik Sense Server September 2017 I'm getting the error.

![issue](https://user-images.githubusercontent.com/9003288/32684092-555168ac-c64e-11e7-8937-1b6525828f99.gif)

**Comment by zucoa** [comment] 2017-11-13 19:06
FYI, I updated to September 2017 patch 1 and still get the connection lost error.

**Comment by rjriel** [comment] 2017-12-13 02:49
So it looks like this is actually a bug in sense....
https://community.qlik.com/thread/275356
We can maybe close this as an issue here but keep track of the updating on this

**Comment by Martin-Tenghagen** [comment] 2017-12-13 07:51
I have one issue filed in Jira already  - should it be re-opened if it´s on Sense side?
Issue 84526 Qlik project

**Comment by stefanwalther** [comment] 2018-01-09 14:36
Please try again, I have fixed this issue with a workaround in version v1.0.0-rc1-03: https://github.com/stefanwalther/sense-navigation/tree/v1.0/build

Hope this helps. Thx @rjriel for your investigations.

**Closed by stefanwalther** 2018-01-09 14:36 UTC
Labels: investigation-needed
