### ISSUE TITLE
Navigate to the sheet in a app 

### ISSUE THREAD

**Issue by vasanth101211** [stefanwalther/sense-navigation#144] opened 2018-05-11 05:14 UTC
### Description

I want to navigate to a sheet with the app name 

### Steps to Reproduce

1. In an open app functionality i tried to add sheet name also but its not redirecting

##### Expected behavior

to redirect to the sheet of the app

##### Actual behavior

not redirecting

##### Operating system

```
[ ] Windows

##### Qlik Sense

```
[ ] Desktop
```

**Comment by stefanwalther** [comment] 2018-07-25 22:53
Which version of _sense_navigation_ are you using?

**Comment by stefanwalther** [comment] 2018-09-16 22:06
I am closing this because I a missing further information to reproduce.

@vasanth101211, please feel free to re-open if the issue still exists based on the newest version (#58 )

**Closed by stefanwalther** 2018-09-16 22:06 UTC
Labels: awaiting answer
