### ISSUE TITLE
v1.0 Beta 06 - allows only 2 actions, no custom style for button

### ISSUE THREAD

**Issue by kunstjan** [stefanwalther/sense-navigation#133] opened 2018-02-11 15:16 UTC
### Description
Hello Stefan,
I'm really looking forward for v1.0 to be finished. I tried to download many versions from your site (see "Steps to Reproduce"), but it still offers me only 2 actions and doesn't offer me possibility for conditional or custom style of a button. Am I stupid and blind or doing another mistake, or is this functionality not implemented yet?

### Steps to Reproduce

1. Downloaded the correct build - tried many:
https://github.com/stefanwalther/sense-navigation/blob/v1.0/build/sense-navigation_latest.zip
https://github.com/stefanwalther/sense-navigation/blob/v1.0/build/sense-navigation_v1.0.0-beta-06.zip
https://github.com/stefanwalther/sense-navigation/raw/master/build/sense-navigation_latest.zip (link or latest version from https://github.com/stefanwalther/sense-navigation/tree/v1.0)
https://github.com/stefanwalther/sense-navigation/blob/master/build/sense-navigation_v0.8.3.zip
https://github.com/stefanwalther/sense-navigation/blob/a14f07d0286c6064174861f6667261354d54dd9f/build/sense-navigation_v1.0.0-beta-05.zip

Then for every downloaded zip one-by-one:
2. deleted old sense navigation versions from my computer
3. created sense-navigation subfolder in my QS Extensions folder
4. extracted zip into sense-navigation
5. put the extension to a new app
6. tried to add actions - after second one, third was not added
7. tried to find in Layout / Style the "Defined by expression" or "Custom style (CSS)" but unsuccessfuly
8. isn't it possible that there is by accident saved old (0.8.3) version into the beta-05 and 06?
9. tried to restart whole QS, did not help...

##### Expected behavior

Expected to work as described in https://github.com/stefanwalther/sense-navigation/tree/v1.0 (more than 2 actions, custom Style for button)

##### Actual behavior

Works as the old version (only 2 actions, only predefined styles)

##### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[x] Desktop
[ ] Enterprise
```

##### Browser

```
[ ] Chrome
[x] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: v1.0 beta 06
* Browser: 
* Qlik Sense: November 2017 Patch 1
* Operating system: Windows 10
* [Other relevant versions]

**Comment by stefanwalther** [comment] 2018-02-13 20:58
Hi, thx for being so patient to wait for 1.0.

Reading your issues from above, I am pretty sure that you are running into a caching problem. Actually Qlik Sense Desktop caches extensions pretty aggressively.

I'd recommend you to do the following:
- Remove (delete the old extension)
- Open Qlik Sense Desktop in your browser (after having opened Qlik Sense Desktop and just minimizing it) through http://localhost:4848
- Remove the old versions of sense-navigation (objects)
- Open Chrome Dev Tools, go to advanced settings and disable cache
- The place the new extension, hit F5 to refresh the browser and place the objects again

In sense-navigation 1.x you'll also see a completely re-organized property panel:

![image](https://user-images.githubusercontent.com/669728/36173352-0e4a8366-1109-11e8-87ee-87aef31451af.png)

... I realize that I will have to write more extensive documentation around this caching problem and how to move to sense-navigation v1.x

Does this help?

**Comment by stefanwalther** [comment] 2018-02-13 20:59
No, if you go to the URL https://github.com/stefanwalther/sense-navigation/tree/v1.0/build, you'll only see new builds.

**Comment by kunstjan** [comment] 2018-02-14 18:14
Hello Stefan,
thank you for your answer - I was almost there, just not refrehing the QS in browser, but in Desktop. I have followed your instructions (I access Chrome Dev Tools only from QS Desktop, don't I? It's not accessible from Firefox, is it?) and it worked for using the extension via web browser but not in Desktop - it is really strange: I have the same app opened in QS Desktop and in Firefox and in Firefox it works perfectly and in Desktop it shows only Apperance tab and nothing more... I have tried F5, Ctrl+F5, Dev tools on, Dev tools off, nothing helps. Do you have any other advice to clean the cache also in Desktop? Isn't there needed to delete some files from my filesystem?
Thanks, Jan

**Comment by stefanwalther** [comment] 2018-02-14 19:11
Make sure you delete the extension first in Desktop entirely (should be located at `"C:\Users\%USERNAME%\Documents\Qlik\Sense\Extensions\sense-navigation"` or something like that).
Firefox does not have Chrome Deve Tools, but the similar stuff (Firefox Developer Tools: https://developer.mozilla.org/son/docs/Tools).

I'll create a guide with step by step instructions + screenshots, that should then hopefully help ... I think we still have some minor misunderstandings.

**Comment by CecilieLeonhardt** [comment] 2018-04-06 11:03
Hi Stefan,

I experience the same problem as Jan, I did everything as described above, but when I use the extension in my desktop version (I just upgraded to february 2018 as I thought that was the issue), I only see the appearance tab. When will your installation guide be available?

Cecilie

**Comment by stefanwalther** [comment] 2018-04-28 21:02
I am still trying to catch and reproduce this error:

- Did you both (@CecilieLeonhardt & @kunstjan) have installed the version < 1.x installed before?
- What are you using:
  - Qlik Sense Desktop
  - Qlik Sense Enterprise (Server)
- Did you have the version < 1.x used in the same app before?

Thx for your answers in advance!

Regards
Stefan

**Comment by CecilieLeonhardt** [comment] 2018-04-29 18:01
Hi Stefan! Thanks for your reply. To answer your questions:
1) Yes, I had the old version before, but I reinstalled Qlik Sense Desktop and deleted all my apps and extensions to make the new version work, but no luck.
2) I am testing your extension on the desktop version before putting the extension up on the server. if I put it on the server, it would also mean that I have to update all the apps that are using the old version of this extension to the new one, right?
3) No, but I have later on tried to add an app which is using the old version to my desktop and the buttons just appear as text.

I hope you will find a solution because the new version sounds great! :)

Regards 
Cecilie

**Comment by CecilieLeonhardt** [comment] 2018-08-28 14:26
Hi Stefan,

I would love to use the new version of this extension, have you found a solution to this issue yet?

**Comment by stefanwalther** [comment] 2018-09-15 22:27
I have just release v1.0-RC-01 ... can you please check, thx?
I have tested various scenarios, but could not reproduce this issue (anymore).

Thx in advance for your feedback!

**Comment by stefanwalther** [comment] 2018-09-17 09:32
The correct location for the download is here:

https://github.com/stefanwalther/sense-navigation/tree/v1.0/build

Direct link: https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_v1.0.0-rc-02.zip

**Comment by CecilieLeonhardt** [comment] 2018-09-17 13:16
Thank you Stefan. Unfortunately I still get an error. I only have access to the appearance tab and there i no button...

**Comment by stefanwalther** [comment] 2018-09-18 00:06
Hi @kunstjan & @CecilieLeonhardt, please try the new RC-03: 

- Direct Download: https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_v1.0.0-rc-03.zip
- Branch: https://github.com/stefanwalther/sense-navigation/tree/v1.0

I found the error:
- In Qlik Sense Desktop and older browsers (like IE 11) JavaScripts `const` and `let` did not work, which actually broken the extension.
- Fixed that now and tested in
  - Qlik Sense Desktop June 2018 (inside the Desktop, not only using http://localhost:4848)
  - Firefox
  - Chrome
  - Edge

Please give it a try an let me know.
Thx a lot in advance!

**Comment by CecilieLeonhardt** [comment] 2018-09-18 04:10
Hej Stefan! 

YAY - it works! Thank you so much!

**Comment by stefanwalther** [comment] 2018-09-18 09:27
Great, thx, then I am closing this issue!

**Closed by stefanwalther** 2018-09-18 09:27 UTC
Labels: awaiting verification, bug
