### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by ArunKrshna** [stefanwalther/sense-navigation#136] opened 2018-03-08 22:49 UTC
### Actions

[Description of the issue]
Extension will be even better if we can have few more Actions, not just 2 actions in the extension.

### Steps to Reproduce
I'm not Java person to give the advice technically.
1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]
Better to have more actions in the extension so that we can show and hide the multiple visualization objects based on actions.
##### Actual behavior

[What actually happened]

### Environment
Qlik Sense 

##### Operating system
Windows 
```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

##### Browser
Internet Explorer
```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment] 2018-03-10 21:14
Which version of sense-navigation did you use? Version 1.x (currently in beta) supports an unlimited amount of actions.
Go here to test v1.x beta: https://github.com/stefanwalther/sense-navigation/tree/v1.0

**Comment by stefanwalther** [comment] 2018-07-26 21:56
^ ping

**Comment by stefanwalther** [comment] 2018-07-26 21:56
@ArunKrshna ^ ping

**Comment by stefanwalther** [comment] 2018-09-16 22:11
I am closing this because of not getting any further information, basically I am not able to reproduce.
Please try the newest version (v1.0 - #58 ).

Thx for your contribution and please feel free to re-open this issue (or create a new one) if the problem continues to exist.

**Closed by stefanwalther** 2018-09-16 22:11 UTC
Labels: question
