### ISSUE TITLE
Select value in field doesn't work

### ISSUE THREAD

**Issue by amien90** [stefanwalther/sense-navigation#62] opened 2016-10-09 21:15 UTC
Field : fieldname
Value : 2016

Doesn't work. Tried also '2016'

I'm i doing something wrong? Using 2.1.1
using the latest Sense-Nav version

**Comment by philippfrenzel** [comment] 2016-10-11 13:04
Hi Stefan, same here - the selection gets ignored - e.g. the unselect all works fine before!
A second button on the page works too ... Console shows error from js-lib?

Thanks Philipp

**Comment by stefanwalther** [comment] 2016-10-19 21:17
Hi @philippfrenzel, could you please post the detailed error from the console, thx.

**Comment by ChryslerSupport** [comment] 2016-10-27 11:24
Hello Stefan, Great extension and my users LOVE IT!  However we are unable to get "select value in field" to work.  we have tried
Value (without Quotes)
'Value'
='Value'
=('Value')
="Value"

Can you please let us know if there is a specific syntax we need to be using...

**Comment by stefanwalther** [comment] 2016-11-15 04:56
Hi, could you pls post a simple sample app or a link to a sample app, thx.

**Comment by ChryslerSupport** [comment] 2016-11-15 15:26
App: Crosstable
Sheet: Button Test

https://www.qlikcloud.com/view/582b28c463bb990001f8ae3a

We love this extension and hope we get to take full advantage of all is has...

Thanks for your review
Larry

**Comment by stefanwalther** [comment] 2016-11-15 16:31
@ChryslerSupport Hmmm, this link doesn't work ... (Resource not found)

**Comment by stefanwalther** [comment] 2016-11-15 16:32
@philippfrenzel Ping, can you send the error?

**Comment by ChryslerSupport** [comment] 2016-11-15 16:44
I am trying to send you the example sense app but it won't let me attach the .qvf file or even a zipped .qvf
In the app, there is no error, just nothing happens on the actions.  The only one I can get to work is set variable.
Other method to get the file to you?

**Comment by philippfrenzel** [comment] 2016-11-16 08:10
Hi, will be able to send it next week - off for viral infection;(

**Comment by stefanwalther** [comment] 2016-11-18 14:46
OK, thx. Get well soon.

**Comment by ChryslerSupport** [comment] 2016-11-29 15:54
Hi, is there an update on this issue?
let me know how I can help...

**Comment by ChryslerSupport** [comment] 2016-12-07 11:48
Hi There,
Has there been an update on the Select Value in Field action behavior?
Please let me know if there is anything that I can do to assist you....
Larry

**Comment by ChryslerSupport** [comment] 2017-01-03 18:57
Happy New Year!
Any progress on the actions recently?  How can I help?
Larry

**Comment by Qlikmeister** [comment] 2017-01-25 16:07
Hi Stefan

Great extension, though I'm having the same issue getting the 'Select Value in Field' option to work.

Let me know if I can send anything to help.

Chris

**Comment by ChryslerSupport** [comment] 2017-01-27 15:28
I found that if you simply type the field name and the value in the fields it works.  If you click to go into the expression editor it doesn't work.  Little quirk but it works great if you STAY OUT of the expression editor.

Thanks
Larry
Chryslersupport

On Jan 25, 2017, at 9:08 AM, Qlikmeister <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stefan

Great extension, though I'm having the same issue getting the 'Select Value in Field' option to work.

Let me know if I can send anything to help.

Chris

-

**Comment by sasqliksense** [comment] 2017-02-22 09:47
Hi Stefan,

I am using the same extension, I am also not able to do the filter based on my criteria.
Please help me out the options I need to select. As of now I am doing below steps.
1. Navigation Behavior -> Navigation Action - None
2.Actions->Actions before navigating - Enabled
     First Action - Select Value in Field
          Field SUBJECT
          Value 'English'

Hi Larry,

I tried your option also, not going to Expression editor and giving the field name and value directly. Still not working for me.

Also please give me the url to download the latest version of this extension

Regards
Sas

**Comment by ChryslerSupport** [comment] 2017-02-22 16:10
I have learned that it works if you DO NOT click on the expression editor button.  Just type the values in the field without going into the expression editor.

Thanks
Larry

**Comment by stefanwalther** [comment] 2018-01-24 07:31
I have tested this extensively in the upcoming v1.0 (see #58) and cannot reproduce anymore.

I am therefore closing this, but feel free to re-open if you find the same issue in the v1.x version.

**Closed by stefanwalther** 2018-01-24 07:31 UTC
Labels: can't reproduce
