### ISSUE TITLE
Button Colouring

### ISSUE THREAD

**Issue by Chricky** [stefanwalther/sense-navigation#99] opened 2017-10-23 08:44 UTC
### Description

The Colouring of the Button via the dropdown menu does not work anymore (Qlik Sense September 2017)

### Steps to Reproduce

1. Add to Sheet
2. Select a Colour via dropdown

##### Expected behavior

When selecting "Danger" from the dropdown menu, the button should be coloured in red, but it does stay white (or more like non-existent)

##### Actual behavior

The button does not change color

### Environment

Server Installation, Microsoft Server 2016 (iirc it is 2016), Qlik Sense September 2017, 

##### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x] Enterprise
```

##### Browser

```
[x] Chrome
[x] Firefox
[x] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: newest
* Browser: Chrome, IE, FF
* Qlik Sense: 2017 September
* Operating system: Win7
* [Other relevant versions]

**Comment by stefanwalther** [comment] 2018-01-09 14:42
Thx for reporting.
@Chricky could you pls open Chrome Dev Tools and post a screenshot if there are any errors. So fare I cannot reproduce this behavior.
Secondly, did you use the v0.x version of the extension or the new v1.x build?

**Comment by stefanwalther** [comment] 2018-01-24 06:40
As I have extensively tested v1.0 (#58), I'll close this issue.
Please feel free to re-open.

**Closed by stefanwalther** 2018-01-24 06:40 UTC
Labels: awaiting answer, investigation-needed
