### ISSUE TITLE
Bookmark Action not Applied

### ISSUE THREAD

**Issue by sidneydrill** [stefanwalther/sense-navigation#141] opened 2018-04-13 02:10 UTC
### Description

The Sheet navigation extension “action” is not properly working after publishing the sheet. Specifically, the "Action" to apply a bookmark is not occurring.  However, It works when NOT published.

### Steps to Reproduce

1.	Create Qlik sheet 1.
2.	Create Qlik sheet 2.
3.	Add extension “Sheet Navigator” on sheet 1. 
a.	Navigation: Go to specific sheet. Pick sheet 2.
b.	Action: apply bookmark. Pick bookmark that applies to sheet 2.
4.	Publish both sheets
5.	Click out of all Qlik dashboards. 
6.	Qlik user 2 sees published sheets 1&2. 
7.	Qlik user 2 selects sheet 1. 
8.	Qlik user 2 clicks extension going to sheet 2.
9.	Qlik user 2 should see new sheet with applied bookmarks.

##### Expected behavior

Published Qlik sheet 1 has navigation button. Qlik user clicks navigation button, and should (1) move to sheet 2, and (b) see bookmark automatically applied to sheet 2. 

##### Actual behavior

Qlik user is moved to sheet 2, but bookmark is NOT applied.

##### Operating system

```
[X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[X ] Enterprise
```

##### Browser

```
[X ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.0
* Qlik Sense: June 2017, Patch 3

**Comment by jurajmisina** [comment] 2018-06-19 15:08
Is the bookmark you're trying to apply a "Base" bookmark or "My" bookmark? For "My bookmarks" this is the behaviour I would expect, because user created bookmarks cannot be shared in Qlik Sense (yet).

**Comment by stefanwalther** [comment] 2018-07-29 21:57
Hmmm, interesting, I'll investigate ...

**Comment by stefanwalther** [comment] 2018-09-19 21:09
@jurajmisina is right, this is the expected baviour when using "My bookmarks" ... I am therefore closing this issue.

Feel free to re-open if you think that does not work as designed.

**Closed by stefanwalther** 2018-09-19 21:09 UTC
Labels: investigation-needed
